# Generated by Django 5.2.6 on 2025-09-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrightDataSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.CharField(max_length=120)),
                ('dataset_id', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=120)),
            ],
        ),
    ]
