# Generated by Django 5.2.6 on 2025-09-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brightdatasnapshot',
            name='error_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
