# Generated by Django 5.2.6 on 2025-09-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0003_redditpost_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditpost',
            name='num_upvotes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
