# Generated by Django 5.2.6 on 2025-09-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0004_redditpost_num_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditpost',
            name='related_posts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
