# Generated by Django 5.2.6 on 2025-09-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0005_redditpost_related_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditpost',
            name='community_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
