# Generated by Django 5.2.6 on 2025-09-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0006_redditpost_community_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditpost',
            name='num_comments',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
