# Generated by Django 5.2.6 on 2025-09-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0007_redditpost_num_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditpost',
            name='community_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
