# Generated by Django 5.2.6 on 2025-09-08 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0009_redditcommunityschema'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RedditCommunitySchema',
            new_name='RedditCommunity',
        ),
    ]
