# Generated by Django 5.2.6 on 2025-09-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0010_rename_redditcommunityschema_redditcommunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditcommunity',
            name='last_scrape_event',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
