# Generated by Django 5.2.6 on 2025-09-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0011_redditcommunity_last_scrape_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditcommunity',
            name='trackable',
            field=models.BooleanField(default=False, help_text='Is this currently being tracked'),
        ),
    ]
